// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "github.com/viktormelnychuk/monoapi/monoapi/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeLoginHandler(m, endpoints, options["Login"])
	makeGetAllTransactionsHandler(m, endpoints, options["GetAllTransactions"])
	makeGetTransactionHandler(m, endpoints, options["GetTransaction"])
	makeGetCardsHandler(m, endpoints, options["GetCards"])
	makeEnableCardHandler(m, endpoints, options["EnableCard"])
	return m
}
